#!/usr/bin/env bash
make stack4
export i=1
export token="A"
while true; do
    echo ""
    echo "Execute:       ./stack4 '$token'"
    echo "Length:        $i"
    ./stack4 "$token"
    if [ $? -eq 0 ]; then
        exit
    fi
    i=$((i+1))
    token="${token}A"
    sleep 0.25 
    
done
