version: '3.5'

services:

    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - 80:80
        volumes:
            - ./:/srv/www/webapp
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            lab4:
                ipv4_address: 172.18.0.2
        depends_on:
            - php

    mysql:
        image: mysql:5.7
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            lab4:
                ipv4_address: 172.18.0.3
        depends_on:
            - php

    php:
        build:
             context: ./docker/php
             dockerfile: Dockerfile
        container_name: php
        ports:
            - 9000:9000
        volumes:
            - ./:/srv/www/webapp
            - ./docker/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
        environment:
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        networks:
            lab4:
                ipv4_address: 172.18.0.4

networks:
    lab4:
        ipam:
            driver: default
            config:
                - subnet: 172.18.0.0/16
