#!/usr/bin/env bash
./cleanup
git clone https://github.com/johnlwhiteman/bad-human-code.git
cd ./bad-human-code
rm -fr .git 
cd ../
git clone https://github.com/SonarSource/sonar-scanning-examples.git
cd sonar-scanning-examples/sonarqube-scanner/src
cp -R * ../../../bad-human-code/
cd ../../../
rm -fr ./sonar-scanning-examples
docker pull sonarqube
#docker pull sonarsource/sonar-scanner-cli
wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.5.0.2216.zip
unzip sonar-scanner-cli-4.5.0.2216.zip 
rm -f sonar-scanner-cli-4.5.0.2216.zip
mv sonar-scanner-4.5.0.2216 sonar-scanner
mv ./sonar-scanner/conf/sonar-scanner.properties ./sonar-scanner/conf/sonar-scanner.properties.BACKUP
cp ./sonar-scanner.properties ./sonar-scanner/conf/sonar-scanner.properties
./startSonarQube
